### ISSUE TITLE
WorldGameRules mess with Comands from Datapackmods.

### ISSUE THREAD

**Issue by suerion** [DrexHD/WorldGameRules#1]
Hey, i had added the WorldGameRules to my huge modpack,

After Adding the mod, i got a lot of issues on Server Side, thought, the datapack mods had an issue, but after disabling it, the datapack work fine again.

I think it is an compatibility issue 

Will add the Issues, i had added on datapacks:

https://github.com/jodeks-datapacks/Sleep/issues/7
https://github.com/Tschipcraft/more_mobs/issues/14
https://github.com/Tschipcraft/dynamiclights/issues/60
https://modrinth.com/datapack/hardcore-revive-reloaded

Dev Enviroment Fabric 1.21.1 with 0.16.5
https://mclo.gs/iKlXez6

**Comment by Jodekq** [comment]
If you use the mod version of my datapack, you could try the datapack version.

**Comment by Tschipcraft** [comment]
Easiest solution would probably be to move the injected dimension selector to the end of the gamerule command and make it optional (default being `@all`)

**Comment by suerion** [comment]
> If you use the mod version of my datapack, you could try the datapack version.

had tried also with Datapacks only, but it has messed also with the functions

**Comment by DrexHD** [comment]
I have pushed a fix, let me know if that resolves your issue!

**Comment by Tschipcraft** [comment]
Lemme check

**Comment by Tschipcraft** [comment]
LGTM, all log errors gone when tested with all four data packs 🎉

**Comment by suerion** [comment]
Thanks for the work :) love the modding community.
